Expanded mgm user model
drift-org/backend pull request #13
Opened 2021-05-28 03:55 UTC by aidenszeto

# Contributors
@aidenszeto 

# Reviewers
@brandonLi8 
@teekenzie 

# Relevant issue
Closes #8 

# Summary of change
- Updated user model to include the fields listed in #8

# Testing/Verification
- Server must compile
- Model fields must accurately represent fields listed in #8

2021-05-28 15:42 UTC, teekenzie commented
Why do we need the 0 in the array. I don't think we need those right?

2021-05-28 17:04 UTC, aidenszeto commented
> Why do we need the 0 in the array. I don't think we need those right?

I think the 0 defaults it to an empty array? I'm pretty sure array sizes have to be known by compiler at compile time too

2021-05-28 18:38 UTC, teekenzie commented
> I think the 0 defaults it to an empty array? I'm pretty sure array sizes have to be known by compiler at compile time too
 
On second thought, you actually have to remove those. You are basically telling Go that we can only have a 0 length array placed into there. 

By not having any number, you could create a dynamic slice and it would still be treated as an array in mongo database

2021-05-28 18:43 UTC, aidenszeto commented
> > I think the 0 defaults it to an empty array? I'm pretty sure array sizes have to be known by compiler at compile time too
> 
> On second thought, you actually have to remove those. You are basically telling Go that we can only have a 0 length array placed into there.
> 
> By not having any number, you could create a dynamic slice and it would still be treated as an array in mongo database

Ok yeah I forgot that you can have dynamic slices in Go, changes should be pushed

2021-05-29 01:12 UTC, teekenzie commented
Also, since you have slice involved in your struct, please also include the creating function. For how to write this function, please refer to the demo-app

2021-05-29 01:15 UTC, aidenszeto commented
> Also, since you have slice involved in your struct, please also include the creating function. For how to write this function, please refer to the demo-app

That's something we can do in a different ticket. This issue is for expanding the user model

2021-05-29 01:24 UTC, teekenzie commented
> That's something we can do in a different ticket. This issue is for expanding the user model

I think this is something that should be included in this ticket. Since this is simply making sure that we won't be running into errors when inserting into database.

2021-05-29 01:28 UTC, aidenszeto commented
> > That's something we can do in a different ticket. This issue is for expanding the user model
> 
> I think this is something that should be included in this ticket. Since this is simply making sure that we won't be running into errors when inserting into database.

2021-05-29 01:29 UTC, aidenszeto commented
> > That's something we can do in a different ticket. This issue is for expanding the user model
> 
> I think this is something that should be included in this ticket. Since this is simply making sure that we won't be running into errors when inserting into database.

I think we should just merge this in and include the route in a different ticket

2021-05-29 01:36 UTC, brandonLi8 commented on models/user_model.go
>  	EmailAddress     string `bson:"email_address" json:"email_address" binding:"required"`
Can we decide on using camel case for json? Seems like snake case is a bit out of place and [google recommends camel case](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format).

2021-05-29 04:54 UTC, brandonLi8 requested changes
> I think we should just merge this in and include the route in a different PR if we wanna stick to one ticket = one PR

I actually agree with @teekenzie on this one. Adding the creating function is associated with your changes and this ticket.

2021-05-29 06:18 UTC, aidenszeto commented
> > I think we should just merge this in and include the route in a different PR if we wanna stick to one ticket = one PR
> 
> I actually agree with @teekenzie on this one. Adding the creating function is associated with your changes and this ticket.

Ok yeah I misinterpreted what was meant by the creating function. Changes are pushed.

2021-05-29 06:53 UTC, teekenzie approved these changes

2021-05-29 23:55 UTC, brandonLi8 approved these changes
lgtm

2021-05-30 21:22 UTC, merged