Patch/#30 - various fixes for create group route
drift-org/backend pull request #36
Opened 2021-06-13 23:03 UTC by brandonLi8

# Contributors

@brandonLi8 

# Relevant issue

Closes #3- (issue)

# Summary of change

1. Use https://pkg.go.dev/github.com/go-playground/validator for unique check (and added missing required, min length check)
2. Make sure that every username provided was found in the database, and return 400 if not
3. Make sure that the user who created the group (bearer) is inside the usernames.
4. Added unit test for create group route

# Testing/Verification

### Manual Tests
Login to get username1's token,
```
curl --location --request POST 'localhost:8080/auth/login' \
-H 'Content-Type: application/json' \
--data-raw '{
    "username": "username1",
    "password": "TestPassword"
}'
```
To test change 1:

```
curl --location --request POST 'localhost:8080/group' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer <token>' \
--data-raw '{
    "usernames": ["username1", "username2",  "username2"]
}'
```

To test change 2:

```
curl --location --request POST 'localhost:8080/group' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer <token>' \
--data-raw '{
    "usernames": ["username1", "username2",  "usernameThatDoesNotExist"]
}'
```

To test change 3:

```
curl --location --request POST 'localhost:8080/group' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer <token for username1>' \
--data-raw '{
    "usernames": ["username2",  "username3"]
}'
```
### Unit Tests
- Added general unit test for create group
- Added spec for each of the manual tests above

2021-06-14 08:04 UTC, anjanbharadwaj commented on controllers/group_controller.go
>  		userIDs[i] = users[i].DefaultModel.IDField.ID
Can change this to just `users[i].ID` instead?

2021-06-14 08:06 UTC, anjanbharadwaj commented on controllers/group_controller.go
> +		context.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "usernames must contain the bearer user"})
Just a personal preference but would be nice to have standardized error messages (at least in terms of capitalizing first letter, punctuation at the end).

2021-06-14 08:06 UTC, anjanbharadwaj commented on controllers/group_controller_test.go
> +	context.Set("userID", user.DefaultModel.IDField.ID.Hex())
same as before, users[i].ID?

2021-06-14 08:08 UTC, anjanbharadwaj requested changes
Mostly LGTM, just some small things here and there and you're good to go.

2021-06-14 19:23 UTC, anjanbharadwaj approved these changes

2021-06-15 01:08 UTC, teekenzie approved these changes

2021-06-15 01:10 UTC, merged